FROM python:3.13-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy app code
COPY . .

# Expose Streamlit port
EXPOSE 8501

# Streamlit config
RUN mkdir -p ~/.streamlit && \
    echo "[client]\nshowErrorDetails = true\n[logger]\nlevel = info" > ~/.streamlit/config.toml

# Run Dashboard
CMD ["streamlit", "run", "src/dashboard/streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]
